<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$isLoggedIn = $customerSession->isLoggedIn();
$msg = $isLoggedIn ? __('Welcome') .', '. $customerSession->getCustomer()->getName() : $this->getWelcome() 
?>
<link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700italic,700,900,900italic' rel='stylesheet' type='text/css'>

<link href='//fonts.googleapis.com/css?family=Poppins:400,300,500,600,700' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Playfair+Display:400,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
<header class="page-header alothemes">
    <div class="header">
		<div class="header-top">
			<div class="container">
				<div class="top-left">
				    <?php echo $this->getChildHtml('store_language'); ?>
				    <?php echo $this->getChildHtml('currency'); ?>
				</div>
				<div class="top-right">
					<div class="header-top-link">
						<?php echo $this->getChildHtml('header.links'); ?>
					</div>
				</div>
			</div>
		</div>
		<div class="header-content">
			<div class="container">
				<div class="row header-main">
					<div class="content-logo col-xs-12 col-sm-12 col-md-3 col-lg-3 main-logo">
						<div class="header-logo">
							<?php echo $this->getChildHtml('logo'); ?>
						</div>
					</div>
					<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 main-search header-search">
						<?php echo $this->getChildHtml('top.search'); ?>
					</div>
					<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 main-right">
					    <div class="header-box">
						    <div class="top-wishlist">
							    <a title="My wishlist" href="<?php echo $this->getUrl('wishlist') ?>" target="_blank" class="btn-heart fa fa-heart"><span class="count counter"><?php echo $this->helper('Magento\Wishlist\Helper\Data')->getItemCount() ?></span></span></a>
							</div>
							<div class="content-cart">
								<?php echo $this->getChildHtml('minicart'); ?>
							</div>
							<div class="menu-mobile">
								 <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<?php echo $this->getChildHtml('navigation.sections'); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
