<?php
if(!$this->getStatus()) return;
$selector = 'alo-content-'.rand(0,999999999);
$slider = $this->getSlider();
if(!count($slider)) return;
?>
<div class="<?php echo $selector ?>">
    <div class="magicslider <?php echo $this->getData('class')?>"
    <?php foreach ($this->getFrontendCfg() as $opt) :?>
        data-<?php echo $opt ?>='<?php echo $this->getData($opt) ?>'
    <?php endforeach;?>  
    data-adaptive-height="true"
    >
        <?php $i=0; foreach ($slider as $item) :?>
            <?php
                if($item['disabled']) continue;
                $image = $item['file'];
                $type  = $item['media_type'];
                $label = $item['label'];
            ?>
			<div class="item <?php echo $type ?>"
                <?php echo ($item['video_url']) ? 'data-video="'. $item['video_url'] .'"' : ''; ?> 
            >
    			<a href="<?php echo isset($item['link']) ? $item['link'] : '#'; ?>">
    				<img class="img-responsive" src="<?php echo $this->getImage($image)?>" alt="<?php echo __($label) ?>" title="<?php echo __($label) ?>" />
    			</a>
				<?php echo isset($item['caption']) ? $item['caption'] : ''; ?>

			</div>
        <?php endforeach ?>
    </div>
</div>

<script type="text/javascript">
    require([
        'jquery',
        'magiccart/slick',
        'alothemes',
        ], function($, slick){
            var magicslider  = $('.<?php echo $selector ?> .magicslider');
            if(magicslider.length) $('head').append(magicproduct(magicslider, '.item'));

    });

    // require([
    //     'jquery',
    //     'fotorama/fotorama',
    // ], function ($, fotorama) {
    //     $('.fotorama').fotorama({
    //         width: 700,
    //         maxwidth: '100%',
    //     });
    // });

</script>
