<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$isLoggedIn = $customerSession->isLoggedIn();
$msg = $isLoggedIn ? __('Welcome') .', '. $customerSession->getCustomer()->getName() : $this->getWelcome() 
?>
<link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700italic,700,900,900italic' rel='stylesheet' type='text/css'>

<link href='//fonts.googleapis.com/css?family=Poppins:400,300,500,600,700' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Playfair+Display:400,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
<header class="page-header alothemes">
    <div class="header">
		<div class="header-top">
			<div class="container">
					<div class="top-left">
						<div class="header-top-link">
							<?php echo $this->getChildHtml('header.links'); ?>
						</div>
					</div>
					<div class="top-right">
						<div class="search-area header-search header-setting click-on-mobile">
							<div class="settting-switcher">
								<div class="dropdown-toggle toggle-tab">
									<div class="icon-search">
										<?php echo __('Search'); ?>
										<i class="fa fa-search"></i>
									</div>
								</div>
								<div class="dropdown-switcher toggle-content">
									<div class="top-search-alo">
										<?php echo $this->getChildHtml('top.search'); ?>
									</div>
								</div>
							</div>
						</div>
						<div class="header-setting tool-header click-on-mobile">
							<div class="settting-switcher">
								<div class="dropdown-toggle toggle-tab">
									<span class="icon"><i class="fa fa-cog"></i></span>
								</div>
								<div class="dropdown-switcher toggle-content">
									<?php echo $this->getChildHtml('currency'); ?>
								    <?php echo $this->getChildHtml('store_language'); ?>
								</div>
							</div>
						</div>
						<div class="content-cart menu-mobile">
						   <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
							<?php echo $this->getChildHtml('minicart'); ?>
						</div>
					</div>
			</div>
		</div>
		<div class="header-content">
			<div class="container">
				<div class="row">
					<div class="content-logo col-md-12 col-sm-12 col-xs-12">
						<div class="header-logo">
							<?php echo $this->getChildHtml('logo'); ?>
						</div>
					</div>
					<div class="col-lg-12">
						<?php echo $this->getChildHtml('navigation.sections'); ?>
						<?php echo $this->getChildHtml('catalog.topnav'); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
